name:                haskell-step-by-step
version:             0.1.0.0
github:              "victor-shneer/haskell-step-by-step"
license:             BSD3
author:              "victor-shneer"
maintainer:          "victor.shneer@gmail.com"
copyright:           "2022 victor-shneer"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/victor-shneer/haskell-step-by-step#readme>

dependencies:
- base >= 4.7 && < 5
- time
- filepath
- directory

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-missing-export-lists
- -Wno-unused-top-binds

library:
  source-dirs: src

executables:
  haskell-step-by-step-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-step-by-step

tests:
  haskell-step-by-step-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-step-by-step
    - hspec
    - time
