# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build_project:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore-cache:
          keys:
            - stack-{{ checksum “stack.yaml” }}
      - restore-cache:
          keys:
            - stack-{{checksum “stack.yaml”}}-{{checksum “project.cabal”}}
      - run: wget https://github.com/commercialhaskell/stack/releases/download/v2.7.5/stack-2.7.5-linux-x86_64.tar.gz -O /tmp/stack.tar.gz
      - run: sudo mkdir /tmp/stack-download
      - run: sudo tar -xzf /tmp/stack.tar.gz -C /tmp/stack-download
      - run: sudo chmod +x /tmp/stack-download/stack-2.7.5-linux-x86_64/stack
      - run: sudo mv /tmp/stack-download/stack-2.7.5-linux-x86_64/stack /usr/bin/stack
      - run: stack setup
      - run: stack test
      - save-cache:
          key: stack-{{ checksum “stack.yaml” }}
          paths:
            - “~/.stack”
      - restore-cache:
          keys: stack-{{checksum “stack.yaml”}}-{{checksum “project.cabal”}}
          paths:
            - “.stack-work”

workflows:
  build_and_test:
    jobs:
      - stack-test
